#!/bin/bash

# all aliases go here...
alias copy="xclip -r -selection clipboard"
# alias mux=tmuxinator
# alias vim=nvim

# # git
# function __git_prompt_git() {
#   GIT_OPTIONAL_LOCKS=0 command git "$@"
# }
# function git_current_branch() {
#   local ref
#   ref=$(__git_prompt_git symbolic-ref --quiet HEAD 2> /dev/null)
#   local ret=$?
#   if [[ $ret != 0 ]]; then
#     [[ $ret == 128 ]] && return  # no git repo.
#     ref=$(__git_prompt_git rev-parse --short HEAD 2> /dev/null) || return
#   fi
#   echo ${ref#refs/heads/}
# }

# alias ga="git add"
# alias gb="git branch"
# alias gbd="git branch -d"
# alias gc="git commit -v"
# alias gco="git checkout"
# alias gcb="git checkout -b"
# alias gd="git diff"
# alias ggpull="git pull origin $(git_current_branch)"
# alias gpsup="git push --set-upstream origin $(git_current_branch)"
# alias gst="git status"
