#!/bin/bash

markdown() {
  open /Applications/Markdown\ Pro.app "$1"
}

function fnd {
  nvim +"Find $*";
}

## to be used in conjunction with `gwt` and a bare repository
##    - needs to be updated to support any bare repository directory
function ch() {
  # get a list of available dirs to cd into
  cd "$HOME/go/src/github.com/couchbasecloud/couchbase-cloud/$1"
}
