#!/bin/bash

markdown() {
  open /Applications/Markdown\ Pro.app "$1"
}

function fnd {
  nvim +"Find $*";
}

## to be used in conjunction with `gwt` and a bare repository
##    - needs to be updated to support any bare repository directory
function ch() {
  if [[ -z "${REPO}" ]]; then
    ECHO "$REPO ENV variable is not set. Unable to change worktrees."
  else
    cd "$REPO/$1"
  fi
}

function psource() {
  source $(poetry env info --path)/bin/activate
}
